In [6]:
from datetime import datetime
from datetime import timedelta
import numpy as np
import pandas as pd
import joblib
import os
from sklearn import preprocessing

In [25]:
reader_new= pd.read_csv("DMS_A_OUTAGE_REPAIR.csv")

In [3]:
reader_new

,OUTAGE_NO,TIME_STAMP,TIME_MOD,REGION_NO,DISTRICT_NO,SUBS_NO,FEEDER_NO,DEV_CAT,DEV_ID,ADDRESS,...,FE_KEY,TEST_MODE,SERVICE_CODE,BUILD_TYPE,BLOCK_MOBILE_OUTBOUND,WORK_TAG_COUNT,SCADA_INITIATED,DERIVED_PRIORITY,PRIORITY_OVERRIDE,EST_RES_DATE
0,207160,10/16/16 0:39,10/17/16 13:58,NaN,1003,2021,25544,DEVICE,RCL_F1605_P621_24923,36 NEWTON RD WOODBRIDGE,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
1,215422,9/25/17 11:17,9/25/17 11:28,NaN,1002,2036,167388,DEVICE,FUSE_F473Y_P576_167333,1185 HIGH ST FAIRFIELD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
2,203982,7/8/16 8:11,7/8/16 8:38,NaN,1004,2040,156193,DEVICE,FUSE_F3657_P1704_156126,859 BOSTON POST RD BUS MILFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
3,213850,8/8/17 7:47,8/8/17 8:15,NaN,1001,2032,12428,CUSTOMER,XFR_F1541_P7561_11730,SMITH AVE 501 NEW HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
4,204038,7/9/16 7:35,7/11/16 14:08,NaN,1004,2004,125356,SERVICE TRANSFORMER,XFR_F2734_P7513_743473,350 KING ST STRATFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
5,203736,7/3/16 7:27,6/5/17 10:35,NaN,1003,2021,28188,SERVICE TRANSFORMER,XFR_F1608_P1034_5885,11 PECK HILL RD WOODBRIDGE,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
6,219662,1/15/18 14:22,1/15/18 14:24,NaN,1004,2003,91441,CUSTOMER,XFR_F2633_P2170_24906,MEADOWVIEW AVE 35 STRATFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
7,213524,7/24/17 6:47,7/25/17 6:47,NaN,1001,2027,57932,DEVICE,FUSE_F1754_P1371_57856,20 FRANKLIN ST NORTH HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
8,208789,12/17/16 12:30,12/17/16 12:54,NaN,1002,2035,131105,CUSTOMER,XFR_F2801_P4256_7270,BEACON HILL TER 45 SHELTON,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
9,213513,7/22/17 14:26,7/24/17 10:07,NaN,1001,2032,18520,SERVICE TRANSFORMER,XFR_F1545_P1745_661,8 HUBBARD RD NORTH BRANFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
10,202801,5/19/16 6:32,5/20/16 11:11,NaN,1004,2011,187860,DEVICE,FUSE_F631_P938_187488,177 MAIN ST 1ST WEST HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
11,220100,2/8/18 18:10,2/9/18 10:30,NaN,1002,2002,98267,CUSTOMER,XFR_F2661_P763_39526,JENNINGS RD 1012 FAIRFIELD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
12,205817,9/6/16 10:12,9/8/16 11:44,NaN,1001,2024,37588,DEVICE,RCL_F1688_P7028_37252,1996 WHITNEY AVE 061 TL 61-249 HAMDEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
13,210928,3/22/17 9:31,3/22/17 9:35,NaN,1002,2026,78572,CUSTOMER,XFR_F2546_P6212_241959,SCOTT ST 65 BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
14,204551,7/19/16 6:01,7/19/16 7:16,NaN,1001,2032,20447,CUSTOMER,XFR_F1548_P130_758,SEA HILL RD 196 NORTH BRANFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
15,220009,2/5/18 9:46,2/6/18 12:37,NaN,1001,2032,11759,SERVICE TRANSFORMER,XFR_F1540_P492_852241,27 WILLIAMS RD NORTH BRANFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
16,208514,12/1/16 2:06,6/8/17 10:59,NaN,1001,2024,46355,DEVICE,FUSE_F1697_P8722_44704,115 BOOTH TER HAMDEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
17,206517,10/3/16 17:45,10/3/16 17:52,NaN,1004,2011,189330,CUSTOMER,XFR_F644_P946_31158,"COURT ST, 206,WEST HAVEN",...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
18,221521,3/3/18 19:58,3/13/18 12:26,NaN,1001,2032,20447,CUSTOMER,XFR_F1548_P1575_449,VALLEY RD 183 NORTH BRANFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
19,219788,1/24/18 10:22,1/25/18 7:46,NaN,1003,2034,140709,SERVICE TRANSFORMER,XFR_F3548_P5060_19941,17 DOME DR SHELTON,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
20,210499,3/8/17 9:42,3/10/17 8:17,NaN,1002,2002,104669,SERVICE TRANSFORMER,XFR_F2673_L33_10270,105 HALF MILE LN SOUTHPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
21,215876,10/7/17 4:14,10/7/17 4:16,NaN,1004,2011,182713,CUSTOMER,XFR_F620_P3262_552396,"LAKE ST, 66,WEST HAVEN",...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
22,205734,8/31/16 15:17,9/1/16 7:30,NaN,1004,2040,155369,SERVICE TRANSFORMER,XFR_F3654_P78_502145,6 HILLSIDE AVE MILFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
23,211569,4/24/17 9:38,3/20/18 8:53,NaN,1002,2026,73734,SERVICE TRANSFORMER,XFR_F2535_P4380_43203,27 CENTER ST BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
24,201340,2/26/16 14:17,2/26/16 19:49,NaN,1002,2026,74610,CUSTOMER,XFR_F2536_P4918_43225,SUBURBAN AVE 22 BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
25,206911,10/10/16 14:49,10/10/16 14:53,NaN,1002,2029,88665,CUSTOMER,XFR_F2626_P8448_37038,ECKART ST 147 BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
26,204014,7/8/16 14:19,7/8/16 15:21,NaN,1004,2004,128812,CUSTOMER,XFR_F2741_P859_41951,WOODSTOCK AVE 436 STRATFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
27,213568,7/27/17 9:30,7/27/17 10:58,NaN,1003,2018,174494,CUSTOMER,XFR_F513_P884_33434,"GROVE ST, 133,2ND,ANSONIA",...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
28,205105,8/8/16 12:42,8/8/16 12:56,NaN,1001,2005,65761,CUSTOMER,XFR_F1902_P6005_41409,CHAPEL ST 1447 204 NEW HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
29,207188,10/17/16 8:47,10/17/16 9:16,NaN,1001,2032,18520,CUSTOMER,XFR_F1545_P1733_4583,"MAPLEVALE CT, 8,EAST HAVEN",...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
30,218556,11/16/17 14:10,11/17/17 6:34,NaN,1004,2004,126333,SERVICE TRANSFORMER,XFR_F2737_P3563_34875,125 SUNFLOWER AVE STRATFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
31,219180,12/22/17 17:14,12/22/17 17:32,NaN,1001,2037,8229,SERVICE TRANSFORMER,XFR_F1526_P10840_41275,95 DWIGHT ST HM NEW HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
32,216801,10/27/17 3:44,11/2/17 6:48,NaN,1002,2016,113614,SERVICE TRANSFORMER,XFR_F2684_P6959_37819,316 CANTERBURY LN FAIRFIELD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
33,206979,10/11/16 21:15,10/12/16 13:37,NaN,1004,2023,143879,DEVICE,FUSE_F3633_P852_143627,6 W RIVER ST MILFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
34,219178,12/22/17 12:14,12/22/17 12:23,NaN,1002,2002,105825,SERVICE TRANSFORMER,XFR_F2676_P4349_38838,52 BRYANT ST BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
35,212017,5/19/17 15:02,5/19/17 15:28,NaN,1004,2003,95250,CUSTOMER,XFR_F2642_P1739_24707,BIRDSEYE ST 2 STRATFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
36,219073,12/17/17 9:30,12/17/17 10:53,NaN,1001,2012,50024,CUSTOMER,XFR_F1704_P4871_6963,ASHLAND PL 59 3RD NEW HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
37,204676,7/22/16 12:32,7/25/16 7:36,NaN,1002,2026,75998,CUSTOMER,XFR_F2540_P5666_567427,INDIAN AVE 20 SIGN BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
38,206199,9/24/16 21:35,9/26/16 8:13,NaN,1002,2002,98267,SERVICE TRANSFORMER,XFR_F2661_P766_39525,1080 JENNINGS RD FAIRFIELD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
39,200599,2/12/16 19:40,2/17/16 6:17,NaN,1003,2001,164909,CUSTOMER,XFR_F3677_P3515_625990,MAIN ST 366 ANSONIA,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
40,204789,7/25/16 16:12,7/25/16 19:29,NaN,1003,2034,138876,CUSTOMER,XFR_F3543_P2453_20339,KANUNGUM TRL 2 B SHELTON,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
41,214417,8/25/17 11:44,8/28/17 10:09,NaN,1001,2033,29226,SERVICE TRANSFORMER,XFR_F1643_P1178_61745,594 SKIFF ST NORTH HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
42,219288,1/2/18 11:37,1/2/18 11:47,NaN,1002,2026,73734,CUSTOMER,XFR_F2535_P3182_42997,HARRAL AVE 305 1ST BRIDGEPORT,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
43,211665,4/29/17 12:42,5/1/17 10:05,NaN,1004,2000,7211,CUSTOMER,XFR_F1442_P3369_32607,CHECK POINT LN 24 WEST HAVEN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
44,219671,1/16/18 15:12,1/17/18 12:27,NaN,1004,2040,156193,CUSTOMER,XFR_F3657_P4018_17687,BOSTON POST RD 910 LFT BCK MILFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
45,218267,11/3/17 19:25,11/6/17 14:11,NaN,1004,2004,128812,SERVICE TRANSFORMER,XFR_F2741_P3609_41890,50 DIANE TER STRATFORD,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
46,218668,11/20/17 20:11,3/14/18 11:13,NaN,1001,2025,62993,CUSTOMER,XFR_F1863_P2684_318434,"CHESTNUT ST, 184,2ND,NEW HAVEN",...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
47,216684,10/25/17 3:07,10/26/17 15:03,NaN,1003,2018,171219,SERVICE TRANSFORMER,XFR_F506_P7663_7817,10 REINER DR SHELTON,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
48,204388,7/18/16 17:07,2/10/17 9:37,NaN,1004,2000,3528,CUSTOMER,XFR_F1433_P1917_15746,KANUGA TRL 513 ORANGE,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN
49,205907,9/11/16 13:28,9/12/16 7:18,NaN,1002,2016,109525,DEVICE,FUSE_F2682_P1149_108597,190 JUDD RD EASTON,...,NaN,NaN,NaN,NaN,0,NaN,NaN,7,0,NaN

In [26]:
def predictionModel(df):

    vectorizer = joblib.load('vectorizer.pkl')
    rf_model = joblib.load('rf_model.pkl')
    gb_model = joblib.load('gb_model.pkl')
    
    #WHAT IF TIME STAMP IS ALSO NULL. WHAT ERROR MESSAGES WILL BE GIVEN THEN
    
    #Features cleaning and filling up null valuesB  B V VVE3
    #For date type features, if their values are not present, make them same as the time stamp
    df["AFRM_DATE"].fillna(df["TIME_STAMP"], inplace=True)
    df["DIAG_DATE"].fillna(df["TIME_STAMP"], inplace=True)
    df["CUR_DEV_TIMESTAMP"].fillna(df["TIME_STAMP"], inplace=True)

    
    #Adding Feature engineering
    df['FE_OUTAGE_DATE'] = pd.to_datetime(df['TIME_STAMP']).dt.date  
    df['FE_OUTAGE_TIME'] = pd.to_datetime(df['TIME_STAMP']).dt.time  
    df['FE_OUTAGE_DAY'] = pd.to_datetime(df['TIME_STAMP']).dt.day  
    df['FE_OUTAGE_MONTH'] = pd.to_datetime(df['TIME_STAMP']).dt.month
    df['FE_OUTAGE_DOW'] = pd.to_datetime(df['TIME_STAMP']).dt.dayofweek
    df['FE_DIAGNOSE_DATE'] = pd.to_datetime(df['DIAG_DATE']).dt.date  
    df['FE_DIAGNOSE_TIME'] = pd.to_datetime(df['DIAG_DATE']).dt.time  
    df['FE_DIAGNOSE_DAY'] = pd.to_datetime(df['DIAG_DATE']).dt.day  
    df['FE_DIAGNOSE_MONTH'] = pd.to_datetime(df['DIAG_DATE']).dt.month
    df['FE_AFRM_DATE_DATE'] = pd.to_datetime(df['AFRM_DATE']).dt.date  
    df['FE_AFRM_DATE_TIME'] = pd.to_datetime(df['AFRM_DATE']).dt.time  
    df['FE_AFRM_DATE_DAY'] = pd.to_datetime(df['AFRM_DATE']).dt.day  
    df['FE_AFRM_DATE_MONTH'] = pd.to_datetime(df['AFRM_DATE']).dt.month
    df['FE_CUR_DEV_DATE'] = pd.to_datetime(df['CUR_DEV_TIMESTAMP']).dt.date  
    df['FE_CUR_DEV_TIME'] = pd.to_datetime(df['CUR_DEV_TIMESTAMP']).dt.time  
    df['FE_CUR_DEV_DAY'] = pd.to_datetime(df['CUR_DEV_TIMESTAMP']).dt.day  
    
    #Remove all extra features: 
    del_features = ['OUTAGE_NO', 'EST_RES_DATE', 'TIME_STAMP', 'TIME_MOD', 'DIAG_DATE', 'REST_DATE', 'REST_CALLBACK_DONE', 'REST_CALLBACK_DATE', 'EST_REPAIR_TIME', 'EST_REPAIR_EXPIRY', 'CURRENT_EST_REPAIR_TIME', 'REGION_NO', 'DISTRICT_NO', 'DEV_ID', 'ADDRESS', 'DEV_NAME', 'SG_KEY', 'PRIMARY_RPT', 'NO_CALLS', 'CUST_AFF', 'CRIT_CUST', 'KVA_AFF', 'CUST_HRS', 'RPTD_DONE', 'RPTD_DATE', 'RPTD_COMT', 'DIAG_DONE', 'DIAG_COMT', 'DISP_DONE', 'DISP_DATE', 'DISP_COMT', 'ARIV_DONE', 'ARIV_DATE', 'ARIV_COMT', 'CAUS_DONE', 'CAUS_DATE', 'CAUS_COMT', 'RPAR_DONE', 'RPAR_DATE', 'RPAR_COMT', 'REST_DONE', 'REST_COMT', 'VERF_DONE', 'VERF_DATE', 'VERF_COMT', 'PHASES', 'AFRM_DONE', 'AFRM_DATE', 'AFRM_COMT', 'HAZARD', 'WORK_ORDER_NO', 'OUTAGE_TYPE', 'EST_OVERRIDE', 'DEV_FPOS', 'CUR_CUST_AFF', 'TOTAL_CUST_AFF', 'CUST_AFF_CHG_DATE', 'PRINT_DATE', 'AVG_MIN_OUT', 'ATTN', 'NEEDS_UPDATE_PRIME_RPT', 'COMMENT_CAT_NO', 'OUTAGE_OAR_CODE', 'LINE_ID', 'LINE_NAME', 'FROZEN_FLAG', 'PEND_DONE', 'PEND_DATE', 'METER_ROUTE', 'METER_CYCLE', 'OUTAGE_COMMENT', 'SUB_AREA', 'NEEDS_CUSTMIN_RECALC', 'SY_STATUS', 'WAS_ORPHANED', 'INCD_DONE', 'INCD_DATE', 'ARCH_DONE', 'ARCH_DATE', 'ABB_INT_ID', 'OP_CENTER_ID', 'IN_SYSTEM', 'JOB_NO', 'OUTAGE_TYPE_KEY', 'BPHASES', 'RELATED_EVENT', 'ITR_EXPIRED_TIME', 'ETR_EXPIRED_TIME', 'MASTER_OUTAGE_NO', 'CBOK_METHOD', 'SECONDARY', 'ORDER_NUMBER', 'SPID', 'WAS_PLANNED', 'REQC_DONE', 'REQC_DATE', 'ALT_DEVICE_FPOS', 'ALT_DEVCAT', 'ALT_DEV_ID', 'RESTORATION_VERIFY', 'KEY_CALL_COMMENTS', 'OP_COMP', 'PRIORITY', 'KEY_CALL_NO', 'PERSONNEL_STANDING_BY', 'EXTERNAL_ID', 'ASSET_DATA_ERROR_FLAG', 'ACK_DONE', 'ACK_DATE', 'CUR_DEV_TIMESTAMP', 'FE_KEY', 'TEST_MODE', 'SERVICE_CODE', 'BUILD_TYPE', 'BLOCK_MOBILE_OUTBOUND', 'WORK_TAG_COUNT', 'SCADA_INITIATED', 'DERIVED_PRIORITY', 'PRIORITY_OVERRIDE','ACCNO', 'OPERATOR']
    for i, item in enumerate(del_features):
        del df[item];
        
        
    #Replacement of null values of features where null values were present
    df['HAZARD_LEVEL_CODE'].fillna(-1, inplace = True)
    df['STAT_CALL'].fillna(0, inplace = True)
    df['HAZARD_COUNT'].fillna(-1, inplace = True)
    
    #Label encoding of each feature
    label_encoder =  preprocessing.LabelEncoder()

    df['CIVIL_DISTR_NAME'] = label_encoder.fit_transform(df['CIVIL_DISTR_NAME'])
    df['CIVIL_DISTR_NAME'].astype('int64')

    #DEV_CAT
    df['DEV_CAT'] = label_encoder.fit_transform(df['DEV_CAT'])
    df['DEV_CAT'].astype('int64')


    #MOMENTARY_OUTAGE : Categorical      
    df['MOMENTARY_OUTAGE'] = label_encoder.fit_transform(df['MOMENTARY_OUTAGE'])
    df['MOMENTARY_OUTAGE'].astype('int64')



    #FE_OUTAGE_DATE  
    df['FE_OUTAGE_DATE'] = label_encoder.fit_transform(df['FE_OUTAGE_DATE'])
    df['FE_OUTAGE_DATE'].astype('int64')

    #FE_OUTAGE_TIME         
    df['FE_OUTAGE_TIME'] = label_encoder.fit_transform(df['FE_OUTAGE_TIME'])
    df['FE_OUTAGE_TIME'].astype('int64')

    df['FE_DIAGNOSE_DATE'] = label_encoder.fit_transform(df['FE_DIAGNOSE_DATE'])
    df['FE_DIAGNOSE_DATE'].astype('int64')

    df['FE_DIAGNOSE_TIME'] = label_encoder.fit_transform(df['FE_DIAGNOSE_TIME'])
    df['FE_DIAGNOSE_TIME'].astype('int64')

    df['FE_AFRM_DATE_DATE'] = label_encoder.fit_transform(df['FE_AFRM_DATE_DATE'])
    df['FE_AFRM_DATE_DATE'].astype('int64')

    df['FE_AFRM_DATE_TIME'] = label_encoder.fit_transform(df['FE_AFRM_DATE_TIME'])
    df['FE_AFRM_DATE_TIME'].astype('int64')

    df['FE_CUR_DEV_DATE'] = label_encoder.fit_transform(df['FE_CUR_DEV_DATE'])
    df['FE_CUR_DEV_DATE'].astype('int64')

    df['FE_CUR_DEV_TIME'] = label_encoder.fit_transform(df['FE_CUR_DEV_TIME'])
    df['FE_CUR_DEV_TIME'].astype('int64')
    
    #Vectorizing the Ouatage comment feature
    outage_cmnt_features = vectorizer.transform(df['OUTAGE_CMNT'])
    comment_df = pd.DataFrame(outage_cmnt_features.toarray(), columns=vectorizer.get_feature_names())
    selected_Features = comment_df.filter(['118', '18', '54', 'and', 'comp', 'crew', 'down', 'information', 'line', 'need', 'ok', 'on', 'open', 'operation', 'p5429', 'pri', 'primary', 'test', 'to', 'tree', 'unknown'], axis=1)
    
    #Since outage comments are now vectorized, deleting the comment feature
    del df['OUTAGE_CMNT']

     #Merge only certain columns of comment dataframe to the original dataframe
    df_total = pd.concat([df, selected_Features], axis=1)
    
    #Deleting all extra columns introduced
    for count,ele in enumerate(df_total.columns):
        if 'Unnamed' in ele:
            del df_total[ele]
    
    #Predicting the data as per each model now
    gb_predictions = gb_model.predict(df_total) 
    rf_predictions = rf_model.predict(df_total)
    
    #Predictions from both the models is available now
    final_predictions = []
    for i in range(len(rf_predictions)):
        if(gb_predictions[i] > rf_predictions[i]):
            final_predictions.append(gb_predictions[i])
        else:
            final_predictions.append(rf_predictions[i])
    
    reader = pd.read_csv("DMS_A_OUTAGE_REPAIR.csv")
    #Removing the pre existing csv now
    os.remove("DMS_A_OUTAGE_REPAIR.csv")
    #Converting hours to Time format as given in time stamp
    
    final_time_array = []
    for count,ele in enumerate(reader['TIME_STAMP']):
        time_str = ele
        date_format_str = '%m/%d/%Y %H:%M'
        given_time = datetime.strptime(time_str, date_format_str)
        n = final_predictions[count]
        final_time = given_time + timedelta(minutes=n)
        final_time_str = final_time.strftime('%m/%d/%Y %H:%M')
        final_time_array.append(final_time_str)

    reader['EST_RES_DATE'] = final_time_array
    #Finally converting it into CSV format  
    reader.to_csv('DMS_A_OUTAGE_REPAIR.csv')

In [27]:
predictionModel(reader_new)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  17 out of  17 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  18 out of  18 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  19 out of  19 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  21 out of  21 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  22 out of  22 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  23 out of  23 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  24 out of  24 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  25 out of  25 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  26 out of  26 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  28 out of  28 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  29 out of  29 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  31 out of  31 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  32 out of  32 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  33 out of  33 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  34 out of  34 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  35 out of  35 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  37 out of  37 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  38 out of  38 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  39 out of  39 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  40 out of  40 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  41 out of  41 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  42 out of  42 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  43 out of  43 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  44 out of  44 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  46 out of  46 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  47 out of  47 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  48 out of  48 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  49 out of  49 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  90 out of  90 | elapsed:    0.0s finished

In [ ]:
reader_new

In [18]:
reader_new= pd.read_csv("DMS_A_OUTAGE_REPAIR.csv")

In [21]:
len(reader_new['TIME_STAMP'])

50

In [19]:
from datetime import datetime
from datetime import timedelta
final_time_array = []
for count,ele in enumerate(reader_new['TIME_STAMP']):
    time_str = ele
    date_format_str = '%m/%d/%Y %H:%M'
    given_time = datetime.strptime(time_str, date_format_str)
    n = reader_new['EST_RES_DATE'][count]
    final_time = given_time + timedelta(minutes=n)
    final_time_str = final_time.strftime('%m/%d/%Y %H:%M')
    final_time_array.append(final_time_str)

reader_new['EEE'] =    final_time_array

ValueError: cannot convert float NaN to integer

In [20]:
reader_new['EEE']

KeyError: 'EEE'

In [ ]:
#These 2 need to be added in the final code

In [ ]:
time_str = '23/2/2020 11:12:22.234513'
date_format_str = '%d/%m/%Y %H:%M:%S.%f'
# create datetime object from timestamp string
given_time = datetime.strptime(time_str, date_format_str)
print('Given timestamp: ', given_time)
n = 15
# Add 15 minutes to datetime object
final_time = given_time + timedelta(minutes=n)
print('Final Time (15 minutes after given time ): ', final_time)
# Convert datetime object to string in specific format 
final_time_str = final_time.strftime('%d/%m/%Y %H:%M:%S.%f')
print('Final Time as string object: ', final_time_str)